import { Card, CardContent } from "@/components/ui/card";

export const metadata = {
  title: "Terms of Service - Payless AI",
  description: "Terms of service for Payless AI VS Code extension and website",
};

export default function TermsPage() {
  return (
    <div className="min-h-screen py-20">
      <div className="container mx-auto px-4 max-w-3xl">
        <h1 className="text-4xl font-bold mb-2">Terms of Service</h1>
        <p className="text-muted-foreground mb-8">Last updated: {new Date().toLocaleDateString()}</p>

        <Card>
          <CardContent className="prose prose-invert max-w-none p-8">
            <section className="mb-8">
              <h2 className="text-2xl font-semibold mb-4">1. Acceptance of Terms</h2>
              <p className="text-muted-foreground leading-relaxed">
                By using Payless AI (&quot;the Service&quot;), you agree to be bound by these Terms of Service. 
                If you do not agree to these terms, please do not use the Service.
              </p>
            </section>

            <section className="mb-8">
              <h2 className="text-2xl font-semibold mb-4">2. Description of Service</h2>
              <p className="text-muted-foreground leading-relaxed">
                Payless AI provides a survey-funded AI coding assistant for VS Code. Users earn credits 
                by completing surveys, which can be spent on AI assistance from various providers including 
                OpenAI, Anthropic, and Google.
              </p>
            </section>

            <section className="mb-8">
              <h2 className="text-2xl font-semibold mb-4">3. User Accounts</h2>
              <ul className="list-disc list-inside text-muted-foreground space-y-2 ml-4">
                <li>You must sign in with a valid Google account to use the Service</li>
                <li>You are responsible for maintaining the security of your account</li>
                <li>You must not share your account with others</li>
                <li>We reserve the right to suspend accounts that violate these terms</li>
              </ul>
            </section>

            <section className="mb-8">
              <h2 className="text-2xl font-semibold mb-4">4. Credits and Usage</h2>
              <ul className="list-disc list-inside text-muted-foreground space-y-2 ml-4">
                <li>Credits are provided free of charge through ad revenue</li>
                <li>Credits have no cash value and cannot be exchanged for money</li>
                <li>Credits may expire or be adjusted at our discretion</li>
                <li>We may modify credit earning rates at any time</li>
                <li>Abuse of the credit system will result in account termination</li>
              </ul>
            </section>

            <section className="mb-8">
              <h2 className="text-2xl font-semibold mb-4">5. Surveys</h2>
              <p className="text-muted-foreground leading-relaxed">
                The Service offers paid surveys through CPX Research. By completing surveys, you agree to:
              </p>
              <ul className="list-disc list-inside text-muted-foreground space-y-2 ml-4 mt-2">
                <li>Provide honest and accurate responses to survey questions</li>
                <li>Not complete surveys using automated tools or bots</li>
                <li>Not manipulate surveys to earn credits fraudulently</li>
              </ul>
            </section>

            <section className="mb-8">
              <h2 className="text-2xl font-semibold mb-4">6. Acceptable Use</h2>
              <p className="text-muted-foreground leading-relaxed">
                You agree not to:
              </p>
              <ul className="list-disc list-inside text-muted-foreground space-y-2 ml-4 mt-2">
                <li>Use the Service for any illegal purpose</li>
                <li>Attempt to bypass credit limits or abuse the system</li>
                <li>Interfere with or disrupt the Service</li>
                <li>Use automated tools to access the Service without permission</li>
                <li>Generate harmful, illegal, or inappropriate content through AI</li>
              </ul>
            </section>

            <section className="mb-8">
              <h2 className="text-2xl font-semibold mb-4">7. AI-Generated Content</h2>
              <p className="text-muted-foreground leading-relaxed">
                AI responses are generated by third-party providers (OpenAI, Anthropic, Google). We do not 
                guarantee the accuracy, completeness, or suitability of AI-generated content. You are 
                responsible for reviewing and validating all AI outputs before use.
              </p>
            </section>

            <section className="mb-8">
              <h2 className="text-2xl font-semibold mb-4">8. Intellectual Property</h2>
              <p className="text-muted-foreground leading-relaxed">
                You retain ownership of your code. We do not claim any rights to code you submit or 
                receive through the Service. The Payless AI extension, website, and branding are our 
                intellectual property.
              </p>
            </section>

            <section className="mb-8">
              <h2 className="text-2xl font-semibold mb-4">9. Limitation of Liability</h2>
              <p className="text-muted-foreground leading-relaxed">
                THE SERVICE IS PROVIDED &quot;AS IS&quot; WITHOUT WARRANTIES OF ANY KIND. WE ARE NOT LIABLE FOR 
                ANY DAMAGES ARISING FROM YOUR USE OF THE SERVICE, INCLUDING BUT NOT LIMITED TO DIRECT, 
                INDIRECT, INCIDENTAL, OR CONSEQUENTIAL DAMAGES.
              </p>
            </section>

            <section className="mb-8">
              <h2 className="text-2xl font-semibold mb-4">10. Modifications</h2>
              <p className="text-muted-foreground leading-relaxed">
                We reserve the right to modify these terms at any time. Continued use of the Service 
                after changes constitutes acceptance of the new terms.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-semibold mb-4">11. Contact</h2>
              <p className="text-muted-foreground leading-relaxed">
                For questions about these terms, contact us at:{" "}
                <a href="mailto:legal@payless.ai" className="text-primary hover:underline">
                  legal@payless.ai
                </a>
              </p>
            </section>
          </CardContent>
        </Card>
      </div>
    </div>
  );
}

